### ISSUE TITLE
Error 404 for Tutorial 2 at http://www.yangdb.org

### ISSUE THREAD

**Issue by docwarems** [YANG-DB/yang-db#107]
http://www.yangdb.org/docs/yangdb-tutorial-advanced.html

**Comment by YANG-DB** [comment]
yes - sorry about this - its still under construction...
will be shortly published

**Comment by YANG-DB** [comment]
Please review the following tutorial pages:
## Instalaiton tutorial
 - https://github.com/YANG-DB/yang-db/blob/develop/docs/tutorial/sample/dragons/installation.md

## schema creation tutorial
- https://github.com/YANG-DB/yang-db/blob/develop/docs/tutorial/sample/dragons/create-ontology.md

## Data Loading tutorial
 - https://github.com/YANG-DB/yang-db/blob/develop/docs/tutorial/sample/dragons/load-data.md

## Query the Graph tutorial
 - https://github.com/YANG-DB/yang-db/blob/develop/docs/tutorial/sample/dragons/query-the-data.md

I would be happy to get some feedback...
